name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
#    - name: Run Spotless Check
#      run: ./gradlew spotlessCheck
    - name: Run Detekt
      run: ./gradlew detekt
    - name: Run Lint
      run: ./gradlew lintDebug
    - name: Install Gems
      run: |
        gem install bundler
        bundle install
    # additional steps here, if neede
    - name: Run Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      run: bundle exec danger
